type: Sqlite # Avaiable types: mysql, sqlite

# SQL
# MySQL Connection string: jdbc:mysql://<host>:<port>/<database>
SQL:
  connection-string: "jdbc:sqlite:path/to/db/sample.db"
  username: "username" # Not required for sqlite
  password: "password" # Not required for sqlite


